### ISSUE TITLE
App stops working if its in background

### ISSUE THREAD

**Issue by ltsharma** [ferrannp/react-native-sync-adapter#19]
Im trying to integrate this in my RN project, every-time app goes background, the app crashes.

**Logcat error output**
 Process: app.my.com, PID: 16407
    java.lang.RuntimeException: Unable to start service com.fnp.reactnativesyncadapter.HeadlessService@89518c2 with Intent { cmp=app.my.com/com.fnp.reactnativesyncadapter.HeadlessService }: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
        at android.app.ActivityThread.-wrap17(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassCastException: host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at com.facebook.react.HeadlessJsTaskService.getReactNativeHost(HeadlessJsTaskService.java:171)
        at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
        at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:52)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
        at android.app.ActivityThread.-wrap17(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417)

**Comment by ferrannp** [comment]
From `host.exp.exponent.MainApplication cannot be cast to com.facebook.react.ReactApplication` it looks like you are using Expo. This module is not compatible with Expo.

**Comment by ltsharma** [comment]
Sorry, my bad, That was ejected expo project but still was working with Expokit.
